#spring:
#  jpa:
#    database: postgresql
#    database-platform: org.hibername.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#  datasource:
#    hikari:
#      maximum-pool-size: 4
#      username: postgres
#      password: postgres
#      driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres

spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha # 태그 정렬 기준
    operations-sorter: method # alpha(알파벳 오름차순), method(HTTP메소드순)
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    doc-expansion: none # tag, operation 펼치는 방식
  api-docs:
    path: /api-docs # html 문서 접속 경로
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**

jwt:
  token:
    expiration-time-ms: 2592000000 # 30일
  secret-key: VlwE34yVB123Yt9V7zq57Tej4MnVUyzblYcfP122Qye3108f7